baseurl = "https://voiretmanger.onrender.com"
languageCode = "fr-fr"

title = "À voir et à manger"

relativeURLs = false
PreserveTaxonomyNames = true
RemovePathAccents = true

[params]
  description = "Chez Nicoflo"

[permalinks]
    post = "/:filename/"

[taxonomies]
  categorie = "categorie"
  tag = "tag"
  annee = "annee"
  acteur = "acteur"
  createur = "createur"
  pays = "pays"
  saga = "saga"
  chef = "chef"
  metteur = "metteur"
  lieu = "lieu"
  festival = "festival"
  
