baseurl = "http://yourSiteHere/"
languageCode = "fr-fr"

title = "À voir et à manger"
[params]
  description = "Chez Nicoflo"
  
PreserveTaxonomyNames = true

Paginate = 6

[permalinks]
    post = "/:filename/"

[taxonomies]
  categorie = "categorie"
  tag = "tag"
  annee = "annee"
  acteur = "acteur"
  createur = "createur"
  pays = "pays"
  saga = "saga"
  chef = "chef"
  metteur = "metteur"
  lieu = "lieu"
  festival = "festival"
